version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - movieapi

  movieapi:
    build:
      context: ./movie.api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
